---
title: "The title"
shorttitle: "Title"
author: 
  - name: Yay-hyung cho
    affiliation: 1
    corresponding: yes    # Define only one corresponding author
    address: Postal address
    email: my@email.com

affiliation:
  - id: 1
    institution: The University of Michigan

abstract: |
  Enter abstract here (note the indentation, if you start a new paragraph).
  
note: |  
  Complete departmental affiliations for each author (note the indentation, if you start a new paragraph).

  Enter author note here.
  
keywords: "keywords"

wordcount: X

class: man
lang: english
figsintext: no
lineno: yes
bibliography:
  - r-references.bib

output: papaja::apa6_pdf
---

```{r message = FALSE, warning = FALSE}
library("papaja")
apa_prepare_doc() # Prepare document for rendering
```


# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Sample

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results

# Discussion

# References
```{r create_r-references}
r_refs(file = "r-references.bib")
```

\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}
\setlength{\parskip}{8pt}
